'use client';

import { useState } from 'react';
import DemoLayout from '@/components/DemoLayout';
import MetricCard from '@/components/MetricCard';
import { Apple, Utensils, Target, TrendingUp, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';

export default function NutritionDemo() {
  const [selectedMeal, setSelectedMeal] = useState('breakfast');
  const [generating, setGenerating] = useState(false);

  const generateMealPlan = () => {
    setGenerating(true);
    setTimeout(() => setGenerating(false), 2000);
  };

  const mealPlans = {
    breakfast: {
      name: 'Power Breakfast Bowl',
      calories: 450,
      protein: 28,
      carbs: 52,
      fat: 15,
      ingredients: [
        '2 eggs (scrambled)',
        '1 cup oatmeal',
        '1/2 avocado',
        '1 cup berries',
        '1 tbsp almond butter',
      ],
      benefits: ['High protein for muscle recovery', 'Complex carbs for sustained energy', 'Healthy fats for hormone production'],
    },
    lunch: {
      name: 'Mediterranean Chicken Bowl',
      calories: 580,
      protein: 42,
      carbs: 48,
      fat: 22,
      ingredients: [
        '6oz grilled chicken breast',
        '1 cup quinoa',
        'Mixed vegetables',
        '2 tbsp olive oil',
        'Feta cheese',
      ],
      benefits: ['Lean protein for satiety', 'Fiber-rich quinoa', 'Anti-inflammatory olive oil'],
    },
    dinner: {
      name: 'Salmon & Sweet Potato',
      calories: 620,
      protein: 38,
      carbs: 55,
      fat: 24,
      ingredients: [
        '6oz wild salmon',
        '1 large sweet potato',
        'Steamed broccoli',
        '1 tbsp coconut oil',
        'Lemon & herbs',
      ],
      benefits: ['Omega-3 fatty acids', 'Vitamin A from sweet potato', 'Cruciferous vegetables'],
    },
  };

  const currentMeal = mealPlans[selectedMeal as keyof typeof mealPlans];

  return (
    <DemoLayout
      title="Nutrition AI"
      description="Personalized meal planning"
      icon={<Apple className="w-6 h-6 text-white" />}
      gradient="from-orange-500 to-yellow-500"
    >
      <div className="space-y-8">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            AI-Powered Nutrition Planning
          </h1>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Personalized meal plans generated by AI based on your goals, preferences,
            dietary restrictions, and nutritional needs.
          </p>
        </div>

        {/* Daily Nutrition Stats */}
        <div>
          <h2 className="text-2xl font-bold text-white mb-6">Today's Nutrition</h2>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <MetricCard
              icon={<Utensils className="w-6 h-6 text-white" />}
              label="Calories"
              value="1,650 / 2,200"
              trend="75%"
              trendUp={true}
              gradient="from-orange-500 to-red-500"
            />
            <MetricCard
              icon={<Target className="w-6 h-6 text-white" />}
              label="Protein"
              value="108g / 150g"
              gradient="from-blue-500 to-cyan-500"
            />
            <MetricCard
              icon={<TrendingUp className="w-6 h-6 text-white" />}
              label="Carbs"
              value="155g / 200g"
              gradient="from-green-500 to-emerald-500"
            />
            <MetricCard
              icon={<Sparkles className="w-6 h-6 text-white" />}
              label="Fats"
              value="61g / 75g"
              gradient="from-yellow-500 to-orange-500"
            />
          </div>
        </div>

        {/* AI Meal Plan Generator */}
        <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold text-white">AI Meal Plan Generator</h2>
            <button
              onClick={generateMealPlan}
              disabled={generating}
              className="px-6 py-3 bg-gradient-to-r from-orange-500 to-yellow-500 text-white rounded-xl font-semibold hover:shadow-lg transition-all disabled:opacity-50 flex items-center gap-2"
            >
              <Sparkles className="w-5 h-5" />
              {generating ? 'Generating...' : 'Generate New Plan'}
            </button>
          </div>

          {/* Meal Selector */}
          <div className="flex flex-wrap gap-4 mb-8">
            {[
              { id: 'breakfast', label: 'Breakfast', time: '7:00 AM' },
              { id: 'lunch', label: 'Lunch', time: '12:30 PM' },
              { id: 'dinner', label: 'Dinner', time: '6:30 PM' },
            ].map((meal) => (
              <button
                key={meal.id}
                onClick={() => setSelectedMeal(meal.id)}
                className={`flex-1 min-w-[200px] p-4 rounded-xl font-semibold transition-all ${
                  selectedMeal === meal.id
                    ? 'bg-gradient-to-r from-orange-500 to-yellow-500 text-white'
                    : 'bg-white/5 text-gray-300 hover:bg-white/10'
                }`}
              >
                <div className="text-lg">{meal.label}</div>
                <div className="text-sm opacity-75">{meal.time}</div>
              </button>
            ))}
          </div>

          {/* Meal Details */}
          <motion.div
            key={selectedMeal}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid md:grid-cols-2 gap-8"
          >
            {/* Meal Info */}
            <div className="space-y-6">
              <div>
                <h3 className="text-2xl font-bold text-white mb-4">{currentMeal.name}</h3>
                
                {/* Macros */}
                <div className="grid grid-cols-4 gap-4 mb-6">
                  <div className="bg-gradient-to-br from-orange-600/20 to-red-600/20 border border-orange-500/30 rounded-lg p-3 text-center">
                    <div className="text-2xl font-bold text-white">{currentMeal.calories}</div>
                    <div className="text-xs text-gray-300">Calories</div>
                  </div>
                  <div className="bg-gradient-to-br from-blue-600/20 to-cyan-600/20 border border-blue-500/30 rounded-lg p-3 text-center">
                    <div className="text-2xl font-bold text-white">{currentMeal.protein}g</div>
                    <div className="text-xs text-gray-300">Protein</div>
                  </div>
                  <div className="bg-gradient-to-br from-green-600/20 to-emerald-600/20 border border-green-500/30 rounded-lg p-3 text-center">
                    <div className="text-2xl font-bold text-white">{currentMeal.carbs}g</div>
                    <div className="text-xs text-gray-300">Carbs</div>
                  </div>
                  <div className="bg-gradient-to-br from-yellow-600/20 to-orange-600/20 border border-yellow-500/30 rounded-lg p-3 text-center">
                    <div className="text-2xl font-bold text-white">{currentMeal.fat}g</div>
                    <div className="text-xs text-gray-300">Fat</div>
                  </div>
                </div>

                {/* Ingredients */}
                <div>
                  <h4 className="text-lg font-semibold text-white mb-3">Ingredients</h4>
                  <ul className="space-y-2">
                    {currentMeal.ingredients.map((ingredient, index) => (
                      <li key={index} className="flex items-center gap-2 text-gray-300">
                        <div className="w-2 h-2 bg-orange-500 rounded-full" />
                        {ingredient}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            {/* Benefits & AI Insights */}
            <div className="space-y-4">
              <div>
                <h4 className="text-lg font-semibold text-white mb-3">Nutritional Benefits</h4>
                <div className="space-y-3">
                  {currentMeal.benefits.map((benefit, index) => (
                    <div
                      key={index}
                      className="bg-green-500/20 border border-green-500/30 rounded-lg p-3 text-gray-200 text-sm"
                    >
                      ✓ {benefit}
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-gradient-to-br from-purple-600/20 to-pink-600/20 border border-purple-500/30 rounded-lg p-4">
                <h4 className="text-lg font-semibold text-white mb-2 flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-purple-400" />
                  AI Recommendation
                </h4>
                <p className="text-gray-300 text-sm">
                  This meal aligns perfectly with your muscle-building goals. The high protein
                  content supports recovery, while complex carbs provide sustained energy for
                  your afternoon workout.
                </p>
              </div>

              <div className="bg-blue-500/20 border border-blue-500/30 rounded-lg p-4">
                <h4 className="text-sm font-semibold text-blue-400 mb-2">Prep Time</h4>
                <p className="text-gray-300 text-sm">15 minutes</p>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Production Features */}
        <div className="bg-gradient-to-r from-orange-600/20 to-yellow-600/20 border border-orange-500/30 rounded-2xl p-8">
          <h2 className="text-2xl font-bold text-white mb-6">Nutrition AI Features</h2>
          <div className="grid md:grid-cols-3 gap-6 text-gray-300">
            <div>
              <h3 className="font-semibold text-white mb-2">Personalization</h3>
              <ul className="space-y-1 text-sm">
                <li>• Dietary preferences & restrictions</li>
                <li>• Calorie & macro targets</li>
                <li>• Food allergies & intolerances</li>
                <li>• Cultural & religious considerations</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-white mb-2">Smart Features</h3>
              <ul className="space-y-1 text-sm">
                <li>• Barcode scanning</li>
                <li>• Recipe import & analysis</li>
                <li>• Restaurant menu lookup</li>
                <li>• Grocery list generation</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-white mb-2">Tracking & Analytics</h3>
              <ul className="space-y-1 text-sm">
                <li>• Macro & micronutrient tracking</li>
                <li>• Meal timing optimization</li>
                <li>• Progress photos & measurements</li>
                <li>• Correlation with fitness data</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </DemoLayout>
  );
}

